Initial run
ThePooN/osu-onlinedb-generator pull request #1
Opened 2020-11-24 17:34 UTC by ThePooN

2020-11-28 12:38 UTC, peppy commented
@ThePooN you'll want to copy a `.sln.DotSettings` file from one of our other repositories (lazer should work fine) and then apply inspections based on that (using resharper or rider to make things easier on yourself).

It will bring things in line with our naming schemes, such as private methods starting with lower-case, statics and consts using different rules etc.

If you aren't using rider/r# you can also see the issues via `inspectcode`, which can be run from cli and dosn't necessarily require a paid license (although you may quality for a free jetbrains subscription under their student clause, in which case i'd definitely recommend that).

2020-11-28 12:43 UTC, peppy requested changes

2020-11-28 12:43 UTC, peppy commented on Generator.cs
> +        private const int step = 18;
where does the number 18 come from here?

2020-11-28 12:43 UTC, peppy commented on Generator.cs
> +            mysql.Clone();
not sure why this is being done here, seems weird/wrong.

2020-11-28 12:43 UTC, peppy commented on Generator.cs
> +                var command = sqlite.CreateCommand();
i think you can just run `sqlite.ExecuteNonQuery(sql)` either directly or via dapper and avoid the need for the array spec weirdness.

2020-11-28 12:43 UTC, peppy commented on Generator.cs
> +                command.CommandText += $"(@beatmap_id{i}, @beatmapset_id{i}, @user_id{i}, @filename{i}, @checksum{i}, @version{i}, @total_length{i}, @hit_length{i}, @countTotal{i}, @countNormal{i}, @
is all this actually needed? if you only select the columns you are inserting no name specifications should be required, and this can just be a `for`/`foreach` loop

2020-11-28 12:43 UTC, peppy commented on Generator.cs
> +            var command = conn.CreateCommand();
add dapper dependency via nuget and `conn.GetSingle<int>("SELECT COUNT(...")` should be able to replace this whole method

2020-11-28 21:52 UTC, ThePooN commented on Generator.cs
> +        private const int step = 18;
On my system, 18 rows in one INSERT statement is the most efficient.

2020-11-28 21:52 UTC, ThePooN commented on Generator.cs
> +            mysql.Clone();
Auto-completion gone wrong.

2020-11-29 00:33 UTC, ThePooN commented on Generator.cs
> +                command.CommandText += $"(@beatmap_id{i}, @beatmapset_id{i}, @user_id{i}, @filename{i}, @checksum{i}, @version{i}, @total_length{i}, @hit_length{i}, @countTotal{i}, @countNormal{i}, @
Not sure I understood, but my changes likely address this I think.

2020-12-11 08:32 UTC, peppy approved these changes

2020-12-11 08:58 UTC, merged